<?php $__env->startSection('content'); ?>

    <!-- begin::page header -->
    <div class="page-header">
        <div>
            <h3>داشبورد</h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">پنل مدیریت</a></li>
                    <li class="breadcrumb-item active" aria-current="page">داشبورد</li>
                </ol>
            </nav>
        </div>

        
            
                
            
            
                
                
                
            
        
    </div>
    <!-- end::page header -->

    <div class="row">
        <div class="col-lg-3 col-sm-12">

            <div class="card overflow-hidden">
                <div class="card-body text-center">
                    <div class="d-flex align-items-center justify-content-center m-b-10">
                        <div class="icon-block icon-block-outline-primary icon-block-floating m-l-20">
                            <i class="ti-user"></i>
                        </div>
                        <h3 class="m-b-0 text-primary font-weight-800 primary-font">آدرس سایت</h3>
                    </div>
                    <p><?php echo e($url); ?></p>
                </div>
                
            </div>

        </div>
        <div class="col-lg-3 col-md-12">

            <div class="card overflow-hidden">
                <div class="card-body text-center">
                    <div class="d-flex align-items-center justify-content-center m-b-10">
                        <div class="icon-block icon-block-outline-danger icon-block-floating m-l-20">
                            <i class="ti-home"></i>
                        </div>
                        <h2 class="m-b-0 text-danger font-weight-800 primary-font"><?php echo e($my_country); ?></h2>
                    </div>
                    <p>نام کشور شما</p>
                </div>
                
            </div>

        </div>
        <div class="col-lg-3 col-md-12">

            <div class="card overflow-hidden">
                <div class="card-body text-center">
                    <div class="d-flex align-items-center justify-content-center m-b-10">
                        <div class="icon-block icon-block-outline-success icon-block-floating m-l-20">
                            <i class="ti-stats-up"></i>
                        </div>
                        <h2 class="m-b-0 text-success font-weight-800 primary-font"><?php echo e(number_format($your_country_rank)); ?></h2>
                    </div>
                    <p>رتبه الکسا در <?php echo e($my_country); ?></p>
                </div>
                
            </div>

        </div>
        <div class="col-lg-3 col-md-12">

            <div class="card overflow-hidden">
                <div class="card-body text-center">
                    <div class="d-flex align-items-center justify-content-center m-b-10">
                        <div class="icon-block icon-block-outline-warning icon-block-floating m-l-20">
                            <i class="ti-world"></i>
                        </div>
                        <h2 class="m-b-0 text-warning font-weight-800 primary-font"><?php echo e(number_format($global_rank)); ?></h2>
                    </div>
                    <p>رتبه الکسا شما در جهان</p>
                </div>
                
            </div>

        </div>
    </div>

    
        
            
            
            
                
                    
                
                
                    
                        
                    
                    
                        
                        
                        
                    
                
            
            
        
    

    
        

            
                
                    
                        
                    
                    
                    
                    
                        
                    
                
            

        
        

            
                
                    
                        
                    
                    
                    
                    
                        
                    
                
            

        
        

            
                
                    
                        
                    
                    
                    
                    
                        
                    
                
            

        
        

            
                
                    
                        
                    
                    
                    
                    
                        
                    
                
            

        
    

    
        
            
                
                    
                    
                    
                
            
        
    

    
        

            
                
                    
                        
                    
                    
                        
                            
                        
                    
                    
                        
                            
                            
                                
                                
                                
                                
                                
                            
                            
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                        
                                            
                                            
                                        
                                    
                                
                                
                                
                                    
                                
                                
                                    
                                
                                
                                    
                                        
                                            
                                        
                                        
                                            
                                            
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                        
                                            
                                            
                                        
                                    
                                
                                
                                
                                    
                                
                                
                                    
                                
                                
                                    
                                        
                                            
                                        
                                        
                                            
                                            
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                        
                                            
                                            
                                        
                                    
                                
                                
                                
                                    
                                
                                
                                    
                                
                                
                                    
                                        
                                            
                                        
                                        
                                            
                                            
                                            
                                        
                                    
                                
                            
                            
                                
                                    
                                        
                                            
                                                
                                            
                                        
                                        
                                            
                                            
                                        
                                    
                                
                                
                                
                                    
                                
                                
                                    
                                
                                
                                    
                                        
                                            
                                        
                                        
                                            
                                            
                                            
                                        
                                    
                                
                            
                            
                        
                    
                
            

            
                
                    
                        
                            
                            
                        
                        
                            
                                
                                
                            
                        
                    
                    
                
            

            
                
                    
                        
                        
                    
                    
                        
                            
                        
                    
                    
                        
                            
                                
                                    
                                        
                                    
                                    
                                
                                
                                    
                                        
                                    
                                    
                                
                                
                                    
                                        
                                    
                                    
                                
                                
                                    
                                        
                                    
                                    
                                
                                
                                    
                                        
                                    
                                    
                                
                            
                        
                    
                
            

            
                
                    
                    
                        
                            
                            
                                
                            
                        
                        
                            
                            
                                
                            
                        
                        
                            
                            
                                
                            
                        
                        
                            
                            
                                
                            
                        
                        
                            
                            
                                
                            
                        
                        
                            
                            
                                
                            
                        
                        
                            
                            
                                
                            
                        
                        
                            
                            
                        
                        
                            
                            
                                
                            
                        
                    
                
            

        
        

            
                
                    
                    
                    
                        
                            
                            
                            
                        
                        
                            
                            
                            
                        
                    
                
            

            
                
                    
                        
                            
                                
                                    
                                
                                
                                    
                                        
                                    
                                    
                                        
                                    
                                    
                                        
                                    
                                    
                                        
                                    
                                    
                                        
                                    
                                
                                
                            
                            
                                
                                    
                                
                                
                                    
                                        
                                    
                                    
                                        
                                    
                                    
                                        
                                    
                                    
                                        
                                    
                                    
                                        
                                    
                                
                                
                            
                            
                                
                                    
                                
                                
                                    
                                        
                                    
                                    
                                        
                                    
                                    
                                        
                                    
                                    
                                        
                                    
                                    
                                        
                                    
                                
                                
                            
                        
                        
                    
                
            

            
                
                    
                    
                    
                        
                    
                    
                    
                    
                
            

            
                
                    
                        
                            
                                
                                    
                                
                                
                                    
                                    
                                        
                                    
                                
                            
                            
                        
                        
                            
                                
                                    
                                
                                
                                    
                                    
                                        
                                    
                                
                            
                            
                        
                        
                            
                                
                                    
                                
                                
                                    
                                    
                                        
                                    
                                
                            
                            
                        
                    
                
            

            
                
                    
                    
                        
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    
                                
                            
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    
                                
                            
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    
                                
                            
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    
                                
                            
                            
                                
                                    
                                        
                                    
                                
                                
                                    
                                    
                                
                                
                                    
                                
                            
                        
                    
                
            

        
    


<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.admin', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>